### ISSUE TITLE
[Feature Request] Support Adhoc adaptative response invocation in Enterprise Security

### ISSUE THREAD

**Issue by tblatrille** [LetMeR00t/TA-thehive-cortex#16]
# Request Type
Feature Request

# Problem Description
Enterprise Security's adaptative response with the TA-Thehive-cortex app is available on the correlation search editor, but not on Incident Review.

# Steps to Reproduce
In the Enterprise Security app when clicking an incident in the incident review dashboard and choose an incident,  "create a hive alert" does not appear as one of the response actions available.

# Possible Solutions
Add 
`param._cam = {"supports_adhoc": true, "technology": [{"vendor": "TheHive-project", "version": ["3.0.0"], "product": "TheHIve"}], "task": ["Investigate"], "subject": ["Alert"], "category": ["Analysis"]}`

 in [alert_actions.conf](https://github.com/LetMeR00t/TA-thehive-cortex/blob/master/TA-thehive-cortex/default/alert_actions.conf) as the [alert_action.conf of TA-Thehive](https://github.com/remg427/TA-thehive/blob/master/TA-thehive/default/alert_actions.conf) legacy app and suggested in [forum solution
](https://community.splunk.com/t5/Splunk-Enterprise-Security/Adaptive-response-actions-wont-show-up/m-p/417386)

**Comment by LetMeR00t** [comment]
Hi,
As explained here : https://github.com/LetMeR00t/TA-thehive-cortex/issues/13 I don’t have a Splunk Enterprise Security on my development environment unfortunately.
I let @remg427 take a look at it to help me
Thank you for your understanding

**Comment by remg427** [comment]
Hi still on todo list I'll get Dev env back next week
-- 
Sent with K-9 Mail.

**Comment by tblatrille** [comment]
@remg427 & @LetMeR00t 
Thanks a lot.
From what I read in #13, we have a different use case but both for sure in the scope of "enhancement of integration between ES and TA-TheHive". 
Best regards,

Tomas

**Comment by LetMeR00t** [comment]
Hi @remg427,
Ask you requested, I've added the Adaptive Response for #13 and #16.
I don't know if this is sufficient to work with Splunk ES, @tblatrille maybe you could test it and see if you have anything new on Splunk ES?
Tell me if you need anything else.
"dev" branch is up to date.

**Comment by tblatrille** [comment]
Hi @LetMeR00t  @remg427,
Thanks a lot for your support.
It's almost working, the adaptive response action now appears in the incident dashboard ! 
But there is a small error when creating the action.
![image](https://user-images.githubusercontent.com/17602895/111784117-47374b00-88bb-11eb-80c8-267edfe9c125.png)
There is a [possible solution in the splunk forum](https://community.splunk.com/t5/Splunk-Enterprise-Security/Splunk-Enterprise-Security-Adaptive-Response-Action-Adhoc/m-p/355828).  Set the params available in the UI in alerts.conf as in [this picture](https://prnt.sc/p40i0c).

Best regards.

**Comment by remg427** [comment]
Hi
Yes some code needs to be added

Le 19 mars 2021 14:04:43 GMT+01:00, tblatrille ***@***.***> a écrit :
>Hi @LetMeR00t  @remg427,
>Thanks a lot for your support.
>It's almost working, the adaptive response action now appears in the
>incident dashboard ! 
>But there is a small error when creating the action.
>![image](https://user-images.githubusercontent.com/17602895/111784117-47374b00-88bb-11eb-80c8-267edfe9c125.png)
>There is a [possible solution in the splunk
>forum](https://community.splunk.com/t5/Splunk-Enterprise-Security/Splunk-Enterprise-Security-Adaptive-Response-Action-Adhoc/m-p/355828).
>Set the params available in the UI in alerts.conf as in [this
>picture](https://prnt.sc/p40i0c).
>
>Best regards.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/LetMeR00t/TA-thehive-cortex/issues/16#issuecomment-802818458

-- 
Sent with K-9 Mail.

**Comment by LetMeR00t** [comment]
Hi,
A new proposal **on the dev branch** was provided partially or totally for this issue.
Could you take a look at this and give us some feedback if this is resolved your issue ?
Thank you

**Comment by tblatrille** [comment]
Hi @LetMeR00t,
Thanks for letting me know.
Unfortunately the error continues.
`ModularActionException: Invalid parameter for adhoc modular action.
`
But as far as I understand in the .conf file there might still be missing some parameters that are present in the UI such as the ones discussed in this [issue.](https://github.com/remg427/TA-thehive/issues/13)
Some could bes:
```
param.caseTemplate =
param.tags = 
param.thehive_instance =
```

**Comment by LetMeR00t** [comment]
@remg427 , is it something I missed on the integration of your code ?

**Comment by LetMeR00t** [comment]
@tblatrille, I understand what you mean but I don't know what I have to set up
![screenshot1](https://user-images.githubusercontent.com/10530375/114882587-636bd080-9e04-11eb-9e4f-be22e81d77f2.png)

As you can see, it asks me for the ad-hoc action two things that I don't know how to configure

**Comment by remg427** [comment]
Hi
param.thehive_instance is mandatory
So it should be present in conf file

I'll check adhoc invokation next week

Le 15 avril 2021 14:11:41 GMT+02:00, tblatrille ***@***.***> a écrit :
>Hi @LetMeR00t,
>Thanks for letting me know.
>Unfortunately the error continues.
>`ModularActionException: Invalid parameter for adhoc modular action.
>`
>But as far as I understand in the .conf file there might still be
>missing some parameters that are present in the UI such as the ones
>discussed in this
>[issue.](https://github.com/remg427/TA-thehive/issues/13)
>Some could be:
>```
>param.caseTemplate =
>param.tags = 
>param.thehive_instance =
>```
>
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/LetMeR00t/TA-thehive-cortex/issues/16#issuecomment-820374193

-- 
Sent with K-9 Mail.

**Comment by tblatrille** [comment]
@remg427 @LetMeR00t Thanks a lot!
I will be attentive to new changes

Best regards,

Tomas

**Comment by tblatrille** [comment]
Hey guys @remg427 @LetMeR00t,
Unfortunately, we have not been able to make it work with ES yet. 

Do you think the next releases might enhance ES integration 😄 ?

Best regards,

Tomas

**Comment by LetMeR00t** [comment]
Hello @tblatrille ,
Sorry for the late answer. I have now access to a Splunk ES instance and I'll take a look as soon as possible to make this work as expected.
Thank you

**Comment by LetMeR00t** [comment]
Hi,
v3.0.0 with a fix for your issue is available.
I close this issue, thank you
