### ISSUE TITLE
Stuck in Configuration Loading

### ISSUE THREAD

**Issue by danblae** [LetMeR00t/TA-thehive-cortex#2]
Hello,

I have cortex app freshly installed on a local 8.1.0 Splunk and when I try to go to configuration it gets stuck in a loading screen. 

I have tried to figure out a work-around by just putting the API-Key and the Login directly into a config file, but I am not sure where and how to put it. I have also tried to debug splunk to see if splunk fails to load any file, but I did not see anything that stood out.

I do believe, that the error could be on my end, but maybe you have advise or an idea on what the issue could be.

**Comment by LetMeR00t** [comment]
Hi,
Did you already have the same issue with a previous version of Splunk ?
Did you have any issue related to this application in your $SPLUNK_HOME/var/log/splunk/splunkd.log ?

**Comment by LetMeR00t** [comment]
Hi @danblae ,
After testing the app on the 8.1.0 version of Splunk, it doesn’t worked.
I’m completely reviewing my code to build it with the App Builder Add-on.
Tomorrow a new working version will be ready I hope to resolve this issue :)

**Comment by danblae** [comment]
Thanks @LetMeR00t !

I have also just tried to use 8.0.0 and it works just fine there. Thanks for this awesome tool!

(I will close the issue because I think it will be resolved soon or older versions of Splunk can be used.)

**Comment by LetMeR00t** [comment]
@danblae ,
Just for your information, I'm working on the new version of the application. I will not be able to publish it today I think because I have to review some new functionalities and the documentation (I will add the possibility to use TheHive).
However, I will work on it this week and it will be available very soon.
Thank you for your understanding.

**Comment by danblae** [comment]
Thanks a lot, the info and your time. The help, that an older version of Splunk fixes the problem temporarily helped me out a lot already.

**Comment by LetMeR00t** [comment]
Hi @danblae ,
The older version of this app was archived.
The new one was accepted on the splunkbase : https://splunkbase.splunk.com/app/5329/
