### ISSUE TITLE
[Error] Creating case

### ISSUE THREAD

**Issue by BlueNG01** [LetMeR00t/TA-thehive-cortex#32]
### Request Type
Error 60

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | ubuntu server
| TheHive version / git hash   | 4

### Problem Description
After configuring accounts and instances on splunk I'm getting error code 60 creating new cases 

![errorhive_cortex](https://user-images.githubusercontent.com/104430882/166215143-1cc7b16c-8e06-4de8-be5b-6c3913cb763d.jpg)

### Steps to Reproduce
1. 
2. 
3. 

### Possible Solutions
-

### Logs (issued from the search.log with logging mode set to DEBUG under Settings/Configuration)
-producing this logs

thehive application.log
2022-04-28 14:49:33,489 [WARN] from akka.actor.ActorSystemImpl in application-akka.actor.default-dispatcher-16 [|] Illegal request, responding with status '400 Bad Request': Unsupported HTTP method: The HTTP method started with 0x16 rather than any known HTTP method from "mysplunkip:port". Perhaps this was an HTTPS request sent to an HTTP endpoint?

splunk command_thehive_create_cases
ERROR   thehive:135 - [TH60-GENERIC-ERROR] THE_HIVE_CONNECTION_ERROR - Error: Error: HTTPSConnectionPool(host='myhiveip', port=9000): Max retries exceeded with url: //api/case/_search?range=all (Caused by SSLError(SSLError(1, '[SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:1091)')))

**Comment by LetMeR00t** [comment]
Hi @BlueNG01,
Are you configuring the Splunk app directly to your TheHive instance ?
You have to know that TheHive must be using HTTPS and this is not offered by the product itself, it needs to be behind a proxy to be under HTTPS.
Without HTTPS, this application will not work unfortunately (it's a mandatory condition for Cloud applications)

**Comment by BlueNG01** [comment]
> Hi @BlueNG01, Are you configuring the Splunk app directly to your TheHive instance ? You have to know that TheHive must be using HTTPS and this is not offered by the product itself, it needs to be behind a proxy to be under HTTPS. Without HTTPS, this application will not work unfortunately (it's a mandatory condition for Cloud applications)

thank you for answering this message
no actually I'm testing but the hive and splunk are on two separated machines
so in order to work with ssl, have I to use something like a reverse proxy? (ngnix for example)

**Comment by LetMeR00t** [comment]
Hi @BlueNG01 ,
Indeed, you have to use a reverse proxy between TheHive and Splunk that will handle the HTTPS

**Comment by LetMeR00t** [comment]
Hi @BlueNG01 , I close this issue as it's not linked to an internal bug of this app.
Thank you
