### ISSUE TITLE
[FEATURE] 

### ISSUE THREAD

**Issue by alirezaallahyaripour** [LetMeR00t/TA-thehive-cortex#35]
### Request Type
Feature Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | CentOS 7
| TheHive version / git hash   |  5

### Feature Description
I had a problem with integrating TheHive V5 to the Splunk app and I can't find the proper option.

### Possible Solutions
Since it's currently not supported by the app it must be developed.

**Comment by LetMeR00t** [comment]
Hi @alirezaallahyaripour,
A new release was published to manage TheHive v5.
Please let me know if you find any issue.
Thank you
