### ISSUE TITLE
Inputs keep loading

### ISSUE THREAD

**Issue by remg427** [LetMeR00t/TA-thehive-cortex#4]
hello,
On tab inputs, loading does not complete (splunk 8.1)
btw would it be possible to merge my app into yours?
Remi

**Comment by LetMeR00t** [comment]
Hi @remg427,
I’ve also noticed that you updated your application :) 

Concerning the problem, what is the version of your Splunk instance ? 
How did you install it ? Using the Splunkbase or the SPL file or the tar.gz file ? 
Is the configuration page working ? 
On your inputs page, could you check with the developer tool which request is not working well (probably a 404 error) and how many errors do you have ? 

Once this said, it’s a good idea to merge our works but of course I would like to continue to work on it with you if you are okay with that ? We could share this project to improve all the possibilities behind that , what do you think ? 
I assume, regarding your name, that we could also work using the French language :)

Thank you for opening an issue anyway

**Comment by remg427** [comment]
Hi,
I downloaded from splunkbase and installed from a file. After restart I get this message
Unable to initialize modular input "thehive_supervisor" defined in the app "TA-thehive-cortex": Introspecting scheme=thehive_supervisor: script running failed (exited with code 1).. 11/17/2020, 5:44:06 AM
and in logs error 404
solnlib.packages.splunklib.binding.HTTPError: HTTP 404 Not Found -- {"messages":[{"type":"ERROR","text":"Not Found"}]}

for merging we can continue in French my email is at gmail.com

**Comment by LetMeR00t** [comment]
Hi,
It's weird, this application is created with the App Builder on a Splunk instance with 8.1 version. I've just tried to install it from the splunkbase using a Splunk version 8.0.2 and it's working.
I will try again on the 8.1 this afternoon.
I say that this is weird because the cortex input is the same kind of inputs (with different fields names) and this one is working (I had the same issue using the Splunk version 7.2.6 without knowing what was the issue...
Is the configuratioin page working well ?

**Comment by LetMeR00t** [comment]
@remg427 ,
I proposed a new test for investigating the issue on #5 , could you check his test on your side too ?

**Comment by LetMeR00t** [comment]
Hi @remg427 ,

Could you install the new version of the app (1.1.2) and see if the bug is resolved ?

Thank you

**Comment by LetMeR00t** [comment]
Hi @remg427 ,
I propose you to follow the #5  issue
I close this issue as it's a duplicate.
