### ISSUE TITLE
[FEATURE] TTP/Procedure output to alert/case

### ISSUE THREAD

**Issue by SecurityJill** [LetMeR00t/TA-thehive-cortex#43]
### Request Type
Feature Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       |  Splunk ES
| TheHive version / git hash   | theHive5 / 2.3.1

### Feature Description
When creating a case or alert, export of TTPs from Splunk alerts/notables to TTP tab (procedures) in theHive similarly to how observables are exported and uploaded.

**Comment by LetMeR00t** [comment]
Hello @SecurityJill ,
Good news, a new version of this application with a complete rework is planned soon.
Tomorrow, I'll proceed with the commits/doc updates in the development branch. If you want to test it directly you can do so but of course I would recommand you to wait for the Splunk validation before.

**Comment by LetMeR00t** [comment]
Hi,
v3.0.0 with a fix for your issue is available.
I close this issue, thank you
