### ISSUE TITLE
External search command 'cortexjobs' returned error code 1. .

### ISSUE THREAD

**Issue by razipoor** [LetMeR00t/TA-thehive-cortex#52]
### Request Type
Bug
When executing the "cortexjobs" command in Cortex, you encounter an error with code 1 This error indicates that the external search command "cortexjobs" cannot be executed and has encountered an issue.
### Work Environment

![image](https://github.com/LetMeR00t/TA-thehive-cortex/assets/50591794/1af45f0e-d96e-4a82-8609-3b28b4d9c0d6)![image](https://github.com/LetMeR00t/TA-thehive-cortex/assets/50591794/b53e5a2e-17f6-4333-87b4-f1ce704cb0c9)![image](https://github.com/LetMeR00t/TA-thehive-cortex/assets/50591794/a8fe316e-5a5c-4d57-aa4c-18e4e205dfd3)
| Question              | Answer
|---------------------------|--------------------
| OS version (ubunto 20.04)       | 
| cortex version 3.2/ git hash   | 

### Problem Description
Describe your problem here

### Steps to Reproduce
1. 
2. 
3. 

### Possible Solutions
-

### Logs (issued from the search.log with logging mode set to DEBUG under Settings/Configuration)
-

**Comment by LetMeR00t** [comment]
Hi @razipoor,

Few questions to help you investigate this:
- Which version of the plugin are you using ? On which version of Splunk ?
- Is it the first install or an update of the application ? Did it worked before the upgrade if so ?

Thank you

**Comment by razipoor** [comment]
version splunk 9
no

**Comment by razipoor** [comment]
@LetMeR00t  hiii  ???

**Comment by LetMeR00t** [comment]
Hi,
I noticed some issues for the cortex part that I need to fix. I’ll work on a next release (v3.0.3) as soon as possible.
Everything on the TheHive side is working as expected for your information

**Comment by razipoor** [comment]
hi @LetMeR00t 
When will the new version be ready?

**Comment by LetMeR00t** [comment]
Hi,
I can’t tell you for sure. I’m managing this app on my personal time and it’s not always easy to find time for it. 
I’ll keep you posted as soon as it’s solved.

**Comment by LetMeR00t** [comment]
Hi @razipoor ,
I've just ran some tests on my side.
No major issue was encountered and after reviewing your configuration, I noticed that you are using HTTP instead of HTTPS.
You have to know that, since the v3.x.x, HTTPS became mandatory and you must have a valid HTTPS configuration accordingly (everything is described in the documentation).

Thank you

**Comment by LetMeR00t** [comment]
Hello 

can you provide me any update ? 

Thank you

**Comment by razipoor** [comment]
hello @LetMeR00t 

I didn't find any documentation for using https. Thank you for guiding me further on how I can do this configuration. If you have any documentation, I would appreciate it.

**Comment by LetMeR00t** [comment]
TheHive is not supporting natively HTTPS so you must use a proxy to secure your instance with HTTPS.
A Google search would let you have it quickly: https://docs.strangebee.com/thehive/setup/configuration/ssl/

As it's not concerning an issue directly to this Splunk app, I close this issue.
Thank you for your comprehension
