### ISSUE TITLE
[BUG] Alert script returned error code 31

### ISSUE THREAD

**Issue by hsohsoler** [LetMeR00t/TA-thehive-cortex#53]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| Add-on Version      |  2.3.1
| TheHive version / git hash   | 4.1.23-1

### Problem Description
When alert in splunk is triggered, we recive this error:
![image](https://github.com/LetMeR00t/TA-thehive-cortex/assets/51417125/9cfb5cd3-afbc-40bc-9399-aa889dc9d6d6)

### Steps to Reproduce
1. 
2. 
3. 

### Possible Solutions
-

### Logs (issued from the search.log with logging mode set to DEBUG under Settings/Configuration)
-

**Comment by LetMeR00t** [comment]
Hi,
From the v2.3.1, it seems that the sys code error is happening from this location:

https://github.com/LetMeR00t/TA-thehive-cortex/blob/9363b2a1e6f91ad9675fc276d0082bee95d560a9/TA-thehive-cortex/bin/common.py#L166C3-L172

Are you sure that the instance ID put in your savedsearch is correct ? Cause it seems that it can't find it in your configuration.

Thank you

**Comment by hsohsoler** [comment]
jajajaja yes indeed I don't have an Instance configured, because I had problems with KVStore in Splunk and I think that when I cleaned up KVStore I fucked all my instances.

We can close this post thank you and sorry.
