### ISSUE TITLE
[BUG] Alert script returned error code 60

### ISSUE THREAD

**Issue by hsohsoler** [LetMeR00t/TA-thehive-cortex#54]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| Add -on version      |  2.3.1
| TheHive version / git hash   | 4.1.23-1

### Problem Description
TheHive Alert is not generated but in Splunk yes
![image](https://github.com/LetMeR00t/TA-thehive-cortex/assets/51417125/3a433e68-b9f2-44d6-9934-329e9b445c1c)

### Steps to Reproduce
1. Trigger alert in Splunk
2. Action: Send alert to TheHive
3. 

### Possible Solutions
-

### Logs (issued from the search.log with logging mode set to DEBUG under Settings/Configuration)
-

**Comment by LetMeR00t** [comment]
Hi,
Could you provide more information about what you have setup as an instance in Splunk for your TheHive instance ?
HTTPS is mandatory so make sure you are using a TheHive instance behind HTTPS
You should probably find more information inside the search.log file about the error.

**Comment by hsohsoler** [comment]
Solved. Proxy host set incorrectly.
