### ISSUE TITLE
Can i collect data from hive/cortex on Splunk?

### ISSUE THREAD

**Issue by Kiorgen** [LetMeR00t/TA-thehive-cortex#57]
I want to collect data from hive and cortex on my splunk app.
How can i do this?

**Comment by LetMeR00t** [comment]
Hi,
This feature is only available from the v3.x.x of the application but you have a dedicated tab named "Inputs" within this application that is used to configure periodic data collection from TheHive.
Did you checked that ?
Thank you

**Comment by LetMeR00t** [comment]
Hi,
Do you need any help on this ?
Thank you

**Comment by Kiorgen** [comment]
Hi!
It working!
Thank you so much
