### ISSUE TITLE
[BUG] Custom fields of the Hive

### ISSUE THREAD

**Issue by dimasix9** [LetMeR00t/TA-thehive-cortex#59]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu 22.04
| TheHive version / git hash   | 3.0.2

### Problem Description

I'm interested in the functionality of the custom fields of the Hive (BusinessUnit, Contact). I see the possibility of adding information to them, after the case has been created. However, I need to pass information to these fields before I start creating a case and doing correlation search in Splunk. I tried to do it by analogy with param.description="...", replacing "description" with the name of a custom field, for example param.contact="...", but it didn't work. 
Please tell me how I could implement the creation and filling of custom fields during the creation of a case in the correlation search Splunk.

**Comment by LetMeR00t** [comment]
Hi @dimasix9,
Custom fields are recovered automatically (normally) from TheHive. If you want ot use them, it's not a param of your alert but one field/value provided in the raw data.
"UC1: Saved search - One single alert" under https://github.com/LetMeR00t/TA-thehive-cortex/blob/main/docs/alert_actions_and_adaptive_response.md#uc1-saved-search---one-single-alert is a good example of what you can do and how as for instance the field "cert-alerted-on" is a custom field.
Let me know if it helped you.
Thank you

**Comment by dimasix9** [comment]
@LetMeR00t 
Thank you a lot. It works pretty fine, exactly what I needed.
