### ISSUE TITLE
Python script errors throwing 'External search command 'thehivecases' returned error code 1. '

### ISSUE THREAD

**Issue by sirscottalot** [LetMeR00t/TA-thehive-cortex#6]
Hi @LetMeR00t i have the same issue and here are the python errors.

01-07-2021 16:05:57.106 ERROR ScriptRunner - stderr from '/opt/splunk/bin/python3.7 /opt/splunk/etc/apps/TA-thehive-cortex/bin/thehive_search_cases.py': Traceback (most recent call last):
01-07-2021 16:05:57.106 ERROR ScriptRunner - stderr from '/opt/splunk/bin/python3.7 /opt/splunk/etc/apps/TA-thehive-cortex/bin/thehive_search_cases.py': File "/opt/splunk/etc/apps/TA-thehive-cortex/bin/thehive_search_cases.py", line 43, in
01-07-2021 16:05:57.106 ERROR ScriptRunner - stderr from '/opt/splunk/bin/python3.7 /opt/splunk/etc/apps/TA-thehive-cortex/bin/thehive_search_cases.py': configuration = Settings("spl, logger")
01-07-2021 16:05:57.106 ERROR ScriptRunner - stderr from '/opt/splunk/bin/python3.7 /opt/splunk/etc/apps/TA-thehive-cortex/bin/thehive_search_cases.py': File "/opt/splunk/etc/apps/TA-thehive-cortex/bin/common.py", line 13, in init
01-07-2021 16:05:57.106 ERROR ScriptRunner - stderr from '/opt/splunk/bin/python3.7 /opt/splunk/etc/apps/TA-thehive-cortex/bin/thehive_search_cases.py': for i in client.inputs:
01-07-2021 16:05:57.106 ERROR ScriptRunner - stderr from '/opt/splunk/bin/python3.7 /opt/splunk/etc/apps/TA-thehive-cortex/bin/thehive_search_cases.py': AttributeError: 'str' object has no attribute 'inputs'
01-07-2021 16:05:57.136 ERROR script - xxxxxxxxxxxxxxxxxxxxx__search6_1610035556.143 External search command 'thehivecases' returned error code 1. .

what do you think the issue might be?

**Comment by LetMeR00t** [comment]
Hi @sirscottalot ,
Did you updated the source code ? 
because I can see that the Settings class is instanciated with « spl, logger » which is weird but maybe it’s a render issue of the log ? 
Which version of TheHive and Splunk do you have ?

**Comment by sirscottalot** [comment]
Hey,

running splunk on ubuntu LTR, splunk is version 8.0.2.1 and hive is version 4,

I can see that the API is calling out succsefully to hive, it seems that its returning no data thou.

I dint make any edits to the source, i did check through to see if there were any syntax errors at first, but im going to try a fresh install of the app again to ensure there's no source code edits made accidently. (btw downloaded form the splunk appstore not github)

cheers

S

**Comment by sirscottalot** [comment]
done a fresh install and still getting the same errors.

cheers

S

**Comment by LetMeR00t** [comment]
Could you detail me what you’ve configured once you installed the app ? Did you add the TheHive input and the configuration page ?

**Comment by sirscottalot** [comment]
![image](https://user-images.githubusercontent.com/77116009/104011499-1a253880-51a6-11eb-8df6-f85ccac4e270.png)

i have configured a Splunk user and left the rest as default. (username and password double checked and correct)

![image](https://user-images.githubusercontent.com/77116009/104011579-404ad880-51a6-11eb-8ab1-10add4d57c87.png)

and added a 'thehive:Supervisor'

i can see within the logs that it is sayign it is working i can also see from the hive that an API call is being made :

![image](https://user-images.githubusercontent.com/77116009/104011681-6a9c9600-51a6-11eb-9a30-a1591bdba440.png)

**Comment by sirscottalot** [comment]
![image](https://user-images.githubusercontent.com/77116009/104011872-b94a3000-51a6-11eb-8e7a-b97440f76c92.png)

this is the error log when i go into the search.log i can see the errors i have already sent.

**Comment by LetMeR00t** [comment]
Thank you for your quick and detailed response.

1) Could you check for me something to be sure about this "configuration = Settings("spl, logger")"
Open the file '/opt/splunk/bin/python3.7 /opt/splunk/etc/apps/TA-thehive-cortex/bin/thehive_search_cases.py'
Could you check the content of the line 43.
Do you have :
- configuration = Settings("spl, logger")
or
- configuration = Settings(spl, logger)
?

2) Enable debug mode in the configuration page, then run the search and check on the logs if you have anything.
Could you also check under /opt/splunk/var/log/splunk/ if you have files starting with "command_" and check if you have anything relevant concerning errors on those files ?

Main problem is that it's saying that "client", which should be an object representing a connection with Splunk, is considered as a simple "string" and don't have the "inputs" attribute.
I want to determine why do you have this error...

Moreover, I can't see if you set your Splunk credentials on the configuration page.
Regarding this point : https://github.com/LetMeR00t/TA-thehive-cortex#add-on-settings, do you set a valid admin Splunk account ? (which will be removed in the next version).

Last point, which account are you using ? Is it an admin account or a simple user account and with which roles ?

Connection with TheHive seems working so the issue is concerning Splunk, let's find out what is it :)

**Comment by sirscottalot** [comment]
currentl line 43 reads "configuration = Settings(spl, logger)"

I have configured it using and admin account with full privileges. and am conducting the search with a full admin account.

I have set to debug mode and run the search again looking in the logs i can see some new error messages.

![image](https://user-images.githubusercontent.com/77116009/104016633-9d4a8c80-51ae-11eb-9c05-658c29eb98b6.png)

looking in the var/log/splunk folder i can see the following debug logs.

![image](https://user-images.githubusercontent.com/77116009/104017088-632dba80-51af-11eb-80e2-5c3ab34bdc9b.png)

I've downloaded straight from the splunk app store. looks to be last updated around 2 months ago.

![image](https://user-images.githubusercontent.com/77116009/104017267-b9026280-51af-11eb-9234-b7d1244e93d5.png)

**Comment by sirscottalot** [comment]
OK so i also added a cortex supervisor (made up one as i haven't got it integrated with hive right now and re run the searches and got the following)

![image](https://user-images.githubusercontent.com/77116009/104018543-dafce480-51b1-11eb-83bc-a7d02f1c1a89.png)

I can see that it has actually pulled back data from hive into splunk (that is a tet case ive made) but its still throwing the same overall error.

**Comment by sirscottalot** [comment]
also within the var/log folder there is content in the command_thehive_cases.log

![image](https://user-images.githubusercontent.com/77116009/104018792-55c5ff80-51b2-11eb-8b86-19baf44df818.png)

It seems you need both a the hive supervisor and a cortex supervisor configured but still not sure what the issue is that the reasults arnt displaying in the splunk dashboard.

**Comment by LetMeR00t** [comment]
You're right, some issues happened when only one instance is provided.
I will work on it, I can"t reproduce your error for the moment but I will do some tests.
I'll keep you informed.

**Comment by sirscottalot** [comment]
No Worries thanks for the help so far :D 

I'm going to check my Splunk settings (as we run some custom rules etc) try it on a fresh build see if its something my end

**Comment by LetMeR00t** [comment]
Let's start with a new version here : https://github.com/LetMeR00t/TA-thehive-cortex/tree/v1.1.4

You can download the SPL file and install it directly.

Could you tell me if it's better or not ?

**Comment by sirscottalot** [comment]
hey so i got it working :D 

had to make some changes (commented out 3 sections of the 'thehive_search_cases.py' script. See below. im not amazing with pyhton but it looks like it cant handle it when there is a 'null' feild. for example if a case has no close or updated time (cause its not been)

![Uploading image.png…]()

**Comment by LetMeR00t** [comment]
> hey so i got it working :D
> 
> had to make some changes (commented out 3 sections of the 'thehive_search_cases.py' script. See below. im not amazing with pyhton but it looks like it cant handle it when there is a 'null' feild. for example if a case has no close or updated time (cause its not been)
> 
> ![image](https://user-images.githubusercontent.com/77116009/104030289-148a1b80-51c3-11eb-94fe-cde753718d7b.png)

Great, could you check the fix I provided before your comment ?
It handle the lines you commented :)

**Comment by sirscottalot** [comment]
yer think we posted at same time :P im pulling your fix now. will update once I reinstall

**Comment by LetMeR00t** [comment]
> yer think we posted at same time :P im pulling your fix now. will update once I reinstall

I don't handle the 3 sections so it could raise en error again :) but if so, I will update my code given your changes.
However, it seems you resolved several issues to make it work because it can't explains the first issue you reported.
You can also try to remove the Cortex instance and have only the TheHive one.

**Comment by sirscottalot** [comment]
hey fresh install from the new version, still have to have both inputs, and still had to comment out the above sections to hande the null error. but it is working now 👍.

**Comment by LetMeR00t** [comment]
Could you provide me both logs with errors please to understand why you have these ? Cause I don't have them on my side with my current data.

**Comment by sirscottalot** [comment]
for when the observables are uncommented.

![image](https://user-images.githubusercontent.com/77116009/104035250-d2b0a380-51c9-11eb-8464-b852cfbe4640.png)

for when the caseenddate is uncommented

![image](https://user-images.githubusercontent.com/77116009/104035485-19060280-51ca-11eb-84bf-dd4f02210204.png)

**Comment by LetMeR00t** [comment]
This is maybe related to the fact that you are using TheHive 4 and that was created with TheHive 3 :) I will provide a fix for that but yes it will be different in the future.
Thanks for the logs

**Comment by LetMeR00t** [comment]
@sirscottalot,
A new fix was provided. Could you test it please ?
Thank you

**Comment by sirscottalot** [comment]
yer happy for you to close. look forward to future releases. 💯
