### ISSUE TITLE
[BUG] splunk redirect to cortex does not work 

### ISSUE THREAD

**Issue by pariarajaee** [LetMeR00t/TA-thehive-cortex#60]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       |  ubuntu 20.04
| TheHive version / git hash   | cortex 3.1.7-1 

### Problem Description
Describe your problem here
I configured the app to connect to cortex and the problem is that when I click on a job id to redirect to cortex I got error.

![image](https://github.com/LetMeR00t/TA-thehive-cortex/assets/55338864/eb17bb20-fa39-4a10-b284-210e171597a6)
 
![image](https://github.com/LetMeR00t/TA-thehive-cortex/assets/55338864/d96ce05c-a2aa-437d-bdee-f40e0fc17dfd)

the problem is the url:

https://192.168.22.75:8000/en-US/app/TA-thehive-cortex/%24result.protocol%24://192.168.22.74:4445/index.html#!/jobs/yqEQxIgBCbd4iphZYdpu

the first part should be replaced with "https" as shown bellow:

https://192.168.22.74:4445/index.html#!/jobs/yqEQxIgBCbd4iphZYdpu

I used the proxy settings when adding new instance but got different errors. if that is the solution please describe how to fillup the fields for proxy with an example.

thanks
### Possible Solutions
-

### Logs (issued from the search.log with logging mode set to DEBUG under Settings/Configuration)
-

**Comment by LetMeR00t** [comment]
Hi 
I’ll check this on my side and provide a fix in a v3.0.3 as soon as possible
Thank you for your submission

**Comment by LetMeR00t** [comment]
Hi again,
Bug confirmed, a fix will be provided in the next v3.0.3.
Thank you

**Comment by pariarajaee** [comment]
thanks the redirection is ok but there is still another problem it should use the account I already set in configuration for authenticating automatically and login but it instead goes to login page

**Comment by LetMeR00t** [comment]
Hello @pariarajaee 
No, this is not supported by the application. You have to connect once to TheHive and then, when you click, you'll access to the content without authentication.
