### ISSUE TITLE
[BUG] error code 1 in integrating thehive with splunk

### ISSUE THREAD

**Issue by pariarajaee** [LetMeR00t/TA-thehive-cortex#61]
### Request Type
Bug 
### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       |  ubuntu 20.04
| TheHive version / git hash   | 5

### Problem Description
I had the problem mentioned in issue #52  the solution worked for cortex but still exists for thehive
I I used a proxy to secure instance with https
it worked for cortex but the error still exists for thehive

![image](https://github.com/LetMeR00t/TA-thehive-cortex/assets/55338864/81a14145-5075-406e-af8f-ee5b27ca50bc)

![image](https://github.com/LetMeR00t/TA-thehive-cortex/assets/55338864/79ed795b-6add-4bf2-9651-e5b7a55d63fa)

![image](https://github.com/LetMeR00t/TA-thehive-cortex/assets/55338864/7b1d8f21-bbde-475f-bfab-b9f552c002a7)

### Possible Solutions
-

### Logs (issued from the search.log with logging mode set to DEBUG under Settings/Configuration)
-

**Comment by LetMeR00t** [comment]
Hi 
You may have the same error code but still I don’t see the relevance with #52 as we are talking about HTTPS issue and not custom fields with none values raising an issue 
Which version are you using ? 
Could you detail the custom field you have in TheHive ? Which type is it ? 

Thank you

**Comment by LetMeR00t** [comment]
Hi @pariarajaee,
Any update ?

**Comment by pariarajaee** [comment]
> Hi @pariarajaee, Any update ?

I updated the title. it was wrong . the problem is what I described in the issue body

**Comment by LetMeR00t** [comment]
Hi
I’ll need more than that to help you solve this.
Did you checked on the Audit logs dashboard to see if any error is raised ?
If the error is managed by my script (most of the time it’s the case) then the audit logs dashboard will help you to find out the issue (you can enable the DEBUG mode on your loggings too to activate more logs especially on the audit dashboard)

If you don’t find anything , try to rerun your search and check the search.log file for any ERROR message showing up, try to run it several time if you don’t have anything as sometimes the error isn’t shown systematically.

Thank you

**Comment by pariarajaee** [comment]
> Hi I’ll need more than that to help you solve this. Did you checked on the Audit logs dashboard to see if any error is raised ? If the error is managed by my script (most of the time it’s the case) then the audit logs dashboard will help you to find out the issue (you can enable the DEBUG mode on your loggings too to activate more logs especially on the audit dashboard)
> 
> If you don’t find anything , try to rerun your search and check the search.log file for any ERROR message showing up, try to run it several time if you don’t have anything as sometimes the error isn’t shown systematically.
> 
> Thank you


there is no error in the logs

this is the log file named command_thehive_search_cases.log

![image](https://github.com/LetMeR00t/TA-thehive-cortex/assets/55338864/48bedae7-ffcc-4ec1-9659-03f06ccba5a7)

I also set debug mode

![image](https://github.com/LetMeR00t/TA-thehive-cortex/assets/55338864/682a2179-2229-48b8-8cc2-604b00844fb0)

but got no log in any of the audit log categories on this page

![image](https://github.com/LetMeR00t/TA-thehive-cortex/assets/55338864/cf54f4bc-a720-4cab-94b9-05d57c0ac5c1)

![image](https://github.com/LetMeR00t/TA-thehive-cortex/assets/55338864/0b493aa5-5988-4bc6-8f2c-b3e7ca1d5e20)

**Comment by LetMeR00t** [comment]
Did you tried the search.log of the job running the command too ?

**Comment by pariarajaee** [comment]
> Did you tried the search.log of the job running the command too ?

would you please explain more. where is that log saved? which command do you mean?

**Comment by LetMeR00t** [comment]
On the panel, open the search that is raising an error and click on the top right to check the job details then click on the search.log link 

A link to help: https://docs.splunk.com/Documentation/Splunk/9.0.5/Search/ViewsearchjobpropertieswiththeJobInspector

**Comment by pariarajaee** [comment]
[searchlog.txt](https://github.com/LetMeR00t/TA-thehive-cortex/files/11934325/searchlog.txt)


> On the panel, open the search that is raising an error and click on the top right to check the job details then click on the search.log link
> 
> A link to help: https://docs.splunk.com/Documentation/Splunk/9.0.5/Search/ViewsearchjobpropertieswiththeJobInspector

![image](https://github.com/LetMeR00t/TA-thehive-cortex/assets/55338864/80010924-9a27-4993-b434-fb1631eed244)

[searchlog.txt](https://github.com/LetMeR00t/TA-thehive-cortex/files/11934334/searchlog.txt)

**Comment by LetMeR00t** [comment]
Hi 
The issue is on your certificate it seems :

requests.exceptions.SSLError: HTTPSConnectionPool(host='192.168.22.76', port=4446): Max retries exceeded with url: /api/v1/user/current (Caused by SSLError(SSLCertVerificationError("hostname '192.168.22.76' doesn't match '192.168.22.74'")))


This issue isn't linked to the application

**Comment by pariarajaee** [comment]
the problem is 

> Hi The issue is on your certificate it seems :
> 
> requests.exceptions.SSLError: HTTPSConnectionPool(host='192.168.22.76', port=4446): Max retries exceeded with url: /api/v1/user/current (Caused by SSLError(SSLCertVerificationError("hostname '192.168.22.76' doesn't match '192.168.22.74'")))
> 
> This issue isn't linked to the application

the problem is that I have cortex and thehive in 2 different machines with 2 different certificates
I added both certificates to the trusted certs and also  at the end of the cacert.pem but still get the verification error.
