### ISSUE TITLE
[BUG] |sendalert newline sequence replacing bug

### ISSUE THREAD

**Issue by Bamfax** [LetMeR00t/TA-thehive-cortex#62]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| Splunk Linux Searchhead Cluster    | 
| TheHive v3.0.2   | 

### Problem Description
TA-thehive-cortex v3.0.2 has the same behavior as v2 on the newline sequences \r \n, making it difficult to get these sequences across unmodified in a alert description, if part of a string. 

Removing the replace() sequence like in the fix for issue #34 would allow to get these sequences across unmodified.

Many thanks in advance.

**Comment by LetMeR00t** [comment]
Hi,
I'll take a review at your issue and keep you posted as soon as possible.
Thank you

**Comment by Bamfax** [comment]
Hi LmR, 

thanks for looking at it. Also for the app, which is a great help and the feature enrichments with v3.

**Comment by LetMeR00t** [comment]
Hi @Bamfax,
I've removed the escape lines from my code in the v3.0.4. I hope it will help you.
I've made some tests on it and it seems that we can have different behavior between using a description from the savedsearch itself and the one from a row of the event.

I took the example in the issue you mentionned. Here are the results:
1) Using the description from the savedsearch itself (so parameter set to "$description$")
![image](https://github.com/LetMeR00t/TA-thehive-cortex/assets/10530375/eacb9773-681e-4e12-af8f-01b9d529e06b)

2) Using the description provided in the row of the events (so parameter set to "description")
![image](https://github.com/LetMeR00t/TA-thehive-cortex/assets/10530375/ea03180d-b1b7-48d4-94a6-35faf184af32)

There is less escape in the first example, which should be better.
I can't do more on that as it's the internal way of working of Splunk.

**Comment by LetMeR00t** [comment]
Hello,
A fix was provided in the next release published today on Splunkbase. Cloud vet need to be provided by Splunk but if you're having an on-premise instance, you can already install the latest version.
I'll close this issue as I consider it should be fixed. If you have any other issue, please raise a new issue.
Thank you
