### ISSUE TITLE
Configuration for Search Head Cluster Missing

### ISSUE THREAD

**Issue by kwizzz** [LetMeR00t/TA-thehive-cortex#67]
Can you please include a `server.conf` that allows replication of ta_thehive_cortex_account.conf and ta_thehive_cortex_settings.conf amongst search head cluster:

```
[shclustering]
conf_replication_include.ta_thehive_cortex_account = true
conf_replication_include.ta_thehive_cortex_settings = true
```

See https://docs.splunk.com/Documentation/Splunk/9.1.0/DistSearch/SHCconfigurationoverview and https://docs.splunk.com/Documentation/Splunk/9.1.0/admin/Serverconf:

```
...
conf_replication_include.<conf_file_name> = <boolean>
* Whether Splunk replicates changes to a particular type of *.conf
  file, along with any associated permissions in *.meta files.
* Default: false
...
```

**Comment by LetMeR00t** [comment]
Hi,

A new version (v3.1) is available and fix your issue.

Thank you

**Comment by webfr** [comment]
Hello @LetMeR00t same issue on cluster on 2.3.2, could we take unsynchronized configured configuration files then push again from deployer? Thanks.
