### ISSUE TITLE
Source Ref Too Long -> Unexpected error: BadRequest

### ISSUE THREAD

**Issue by kwizzz** [LetMeR00t/TA-thehive-cortex#70]
When I switch from ES Mode to Alert Mode, some additional string is added to sourceRef:

```
sourceRef = "SPLUNK_JOB:"+ helper.sid + newSource
sourceRef = "SPLUNK_JOB:"+ helper.sid + alert_reference_time
```

(see code starting at https://github.com/LetMeR00t/TA-thehive-cortex/blob/597445b60ba2372f97c4076f3c8e24a8590f530f/TA-thehive-cortex/bin/ta_thehive_cortex/modalert_thehive_common.py#L166C10-L166C10)

This regularly results in an Unexpected error: BadRequest, as the string length is greater than 128

```
...
(!isEmpty(SPLUNK_JOB:<too long string>) && (!143 < 0) && (!143 > 128))
...
```
(143 is the string length of `SPLUNK_JOB:<too long string>`)

Especially `newSource` can be a string of arbitrary length, but most of the time `alert_reference_time` causes the length>128 characters error.

**Comment by LetMeR00t** [comment]
Hi
Thank you for your submission 
I’ll take a look to find a more suitable solution for the next release

**Comment by LetMeR00t** [comment]
Hi,

A new version (v3.1) is available and fix your issue.

Thank you
