### ISSUE TITLE
[BUG] UC2: Columns are missing in screenshot

### ISSUE THREAD

**Issue by kwizzz** [LetMeR00t/TA-thehive-cortex#75]
Just a small nitpick: the columns `cert-alerted-on` and `risk` defined in SPL are missing in the next screenshots.

UC2 in `alert_actions_and_adaptive_response.md`

**Comment by LetMeR00t** [comment]
Hello @kwizzz ,
After a check, it seems that everything is right in the documentation, could you provide me a screenshot on where is the error you've seen ?
Thank you

**Comment by kwizzz** [comment]
Blimey, you are right!  I wasn´t aware that both, `cert-alerted-on` and `risk`, were defined as custom fields.  I was so focused on the newly created table in the TheHive screenshot (where I did not find these fields) that I did not look down to the CF section.
No bug, then.  Sorry.
