### ISSUE TITLE
[BUG] Exclude tags field from markdown table

### ISSUE THREAD

**Issue by kwizzz** [LetMeR00t/TA-thehive-cortex#77]
### Request Type
Bug

### Work Environment

v3.1 Queen

### Problem Description

Fields used for tags should not be in the final markdown table.

### Steps to Reproduce
1. Take SPL from UC2
2. Add another field tag with whatever values
3. In Splunk action, define Tags as $result.tag$
4. Enable generation of markdown table

I think that tags should never end up in the resulting table (as opposed to observables which make sense depending on the scenario).

**Comment by LetMeR00t** [comment]
Hello @kwizzz ,
A fix was provided for this issue, it will be available soon.
Thank you for your submission
