### ISSUE TITLE
[BUG] If uniqueness gets violated, then all remaining results will be skipped

### ISSUE THREAD

**Issue by kwizzz** [LetMeR00t/TA-thehive-cortex#78]
### Request Type
Bug

### Work Environment

v3.1 Queen

### Problem Description & Steps to Reproduce

Take UC2 and modify each `unique` calculation from
`unique=tostring(now())+".1"`
to
`unique=tostring(0)+".1"`

Send the results to TheHive -> two alerts are generated

Now, send it again.  As the first two events have the same `unique` string, no new alert is generated.  Also, you will get an error.  Which is correct.

But processing stops after this -- I would have expected the remaining event with `unique=tostring(now())+".2"` again to be treated to create a new alert.

**Comment by LetMeR00t** [comment]
Hi @kwizzz ,
A fix was provided for this issue and will be push soon.
Thank you for your submission
