### ISSUE TITLE
[FEATURE] Multi-InstanceId Support: Create Alerts&Cases with per-Event HiveInstanceId and allow querying Alerts/Cases from all InstanceIDs of a Server

### ISSUE THREAD

**Issue by Bamfax** [LetMeR00t/TA-thehive-cortex#81]
Hi @LetMeR00t,

we are currently ramping up our number ofTheHive Instances, using a setup where several instances are residing on a server.  

The alert creation is done via the Create Alert custom alert action of splunk queries. As the instance id is configured statically on the alert action, we are using several splunk searches, one per instance id, to export the alerts to the various thehive instances. 

Would it be possible to have the instance id on the a splunk event, so it can be read from there (we are using a "for each result" custom alert action trigger) and with that have a per-event instance selection, easing the need to have multiple exporter searches?

For reading back the alerts and cases from TheHive into Splunk, we are using the spl external command ```"| thehivealerts `hiveProdInstanceId`"```. To get all the alerts, we loop this command to step through all instances. Would it may be possible to enhance that command so that it can get the content from all instances of a specific server automatically? This would also be a great improvement for those specific multi-instance setups.

Looking at the instance configuration, there is also the "Organization" which we currently have blank, as we are using the instance id to address the organization. If there is different way to drive those multi-instance setups, that would allow omit specifying the instance id, I'd be happy to hear. What would also be a nice enhancement would be to have a "comment" field per instance, so some naming or context could be provided with each instance.

Thanks a lot for your consideration and help!
Oliver

**Comment by LetMeR00t** [comment]
Hello @Bamfax , 
Just to be sure to understand, you want:
1) To be able to get alerts/cases from one or several instances of TheHive at once using the custom commands
2) You want to be able to dynamically use an instance ID provided in the results of a Splunk search within your custom alert actions by specifying something like "$result.instance_id$"? (it might already work)
3) You want to be able to add a free comment for each instance added/configured in the application to get more context about a given instance

Additionally, I would like to add that the concept (on my mind) is:
- One instance per customer (customer1, customer2 etc.)
- One organization per team for a given customer (teamA for customer1 and teamB for customer1)

Anyway, for now, the custom alerts actions are using a given instance ID to deduce all the parameters to use (including the organization used by a given instance). You could eventually think of having several instances configured but all pointing to the same TheHive instance but with different organizations. Anyway, the instance ID is always used as the main key to retrieve all the context for a given instance.

Thank you

**Comment by Bamfax** [comment]
Hi @LetMeR00t,

thanks a lot for your reply. Yes, that's exactly the way we would like to drive it, as you have written. Right now we have several teams, 1:1 mapped onto an organization per team in TheHive. Each team also has separate prod & dev instances, residing on different servers. 

What would be nice is if we could create cases/alerts with a per-alert/case instance id. I will give the $result.instance_id$ with a "for each result" trigger as shot and let you know, that's what I also had in my head to try next.

Next, it would be very convenient if we could pull all cases/alerts from a server with a single call of `"| thehivealerts", even if there a several instances configured on this server. I problem to overcome could be here that we are using a per-instance-account&key setup. This would probably need to be unified to a global per-server user, if that's possible from TheHive side. 

And for the instance csv lookup, I thought it would be nice to have a further comment field, in which I can put a separate naming convention for flagging out the team name and the prod/dev instance type, to allow easier identification from userland spl, e.g. through a macro like``` `get_instance_id(team_name, env_name)` ```

**Comment by Bamfax** [comment]
Hi @LetMeR00t,

I tested the above: Using a field from the eventstream like $result.instance_id$ to parameterize the "create alert" custom alert action, combined with a "for each result" trigger on it works like a charm. So that's already a checkmark.

Thanks and happy xmas!

**Comment by LetMeR00t** [comment]
Hi @Bamfax ,

> Next, it would be very convenient if we could pull all cases/alerts from a server with a single call of `"| thehivealerts", even if there a several instances configured on this server. I problem to overcome could be here that we are using a per-instance-account&key setup. This would probably need to be unified to a global per-server user, if that's possible from TheHive side.

I'll work on something to have something working for several instances at once (given several instance ID)

> And for the instance csv lookup, I thought it would be nice to have a further comment field, in which I can put a separate naming convention for flagging out the team name and the prod/dev instance type, to allow easier identification from userland spl, e.g. through a macro like`get_instance_id(team_name, env_name)`

I'll add two new parameters to the lookup instance in the next release ("environment" and "comment") such as:

![image](https://github.com/LetMeR00t/TA-thehive-cortex/assets/10530375/801d234a-b22b-434b-9119-bb6de736219c)
In red, the "environment" parameter and in blue (sorry the input field is hidden), the comment parameter.

For the macro, I'll not add it as it's a specific thing for me but you can add it on your own.
You could use something like:
```
| appendpipe [| inputlookup thehive_cortex_instances | search environment="$environment$" AND comment="*$comment$*" | table id]
```

> I tested the above: Using a field from the eventstream like 
 to parameterize the "create alert" custom alert action, combined with a "for each result" trigger on it works like a charm. So that's already a checkmark.

Thank you for testing

**Comment by LetMeR00t** [comment]
FYI, I just developed the feature to support multiple instances for a get or create alert/case.
You'll just have to give the list of instances as a string separated by a comma such as "instance1_id,instance2_id".
It'll be available in a next release soon but I'll push it to the `develop` branch right now

**Comment by Bamfax** [comment]
Hi @LetMeR00t,

now that was lightning fast. Many thanks a heap lot for implementing those. That is awesome! Especially the "get alerts" functionality, as this will ease stepping over the several instances individually. Does this work with individual accounts per instance as well? Are you then looping over the API internally?

It probably won't get around to switch to a new release before mid or end of January. I will update you once I have switched and tested it.

Thanks a lot and a happy xmas!

**Comment by LetMeR00t** [comment]
Hello @Bamfax 

> now that was lightning fast. Many thanks a heap lot for implementing those. That is awesome! Especially the "get alerts" functionality, as this will ease stepping over the several instances individually. Does this work with individual accounts per instance as well? Are you then looping over the API internally?

Yes, you can use one account per instance as I'm focusing on using only the instance ID information (so the rest can be what you want). I'm looping the process of it through every instance identified. If you can perform some tests and ensure the efficiency is good ;)

> It probably won't get around to switch to a new release before mid or end of January. I will update you once I have switched and tested it.

v3.3 will be release next week probably so go for this one for your tests.

Happy christmas to you too.
