### ISSUE TITLE
Port Connectivity [BUG] 

### ISSUE THREAD

**Issue by Ogwardd** [LetMeR00t/TA-thehive-cortex#83]
### Request Type
**Question**

Hi, been looking into setting this up, our environment is very segregated. Could you please let me know what ports will need to be opened for Splunk and The Hive to communicate?

Thanks!

**Comment by LetMeR00t** [comment]
Hello 
The interaction is from Splunk to TheHive 
You can decide which port you want to use as it’s fully configurable 
Thank you

**Comment by Ogwardd** [comment]
Thanks!
