### ISSUE TITLE
[BUG] Observables that have to be in custom fields

### ISSUE THREAD

**Issue by tsserg99** [LetMeR00t/TA-thehive-cortex#86]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu 22
| TheHive version / git hash   | 5.2.5-1

### Problem Description
Based on my notable results, I create TheHive case from the "sendalert" command. In these cases, I have some observable fields that must be in custom fields such as `status_label, vendor_product, search name,` etc.
I have already added these fields to custom fields in The Hive (screenshot 1), and there aren't these fields in `thehive_datatypes.csv` (screenshot 2), but I have them in TheHive case (screenshot 3)

### Steps to Reproduce
1. Search notable using `event_id`
2. Create TheHive case using `sendalert` command
```
`notable(Threat - CrowdStrike Malware Detected - Rule)` 
| search event_id="3BF73BC1-BCBC-4C65-90EE-FDD1429A4153@@notable@@51fe4306c340c438106014709f606b77" 
| head 1 
| eval th_severity=case(urgency="low",1, urgency="medium",2, urgency="high",3, urgency="critical",4, 1=1,2), incident_title="SOC#".strftime(now(),"%Y%m%dX") 
| table th_severity event_hash _time incident_title ncscc_tag urgency owner_realname comment disposition_label status_label search_name vendor_product orig_sourcetype cim_entity_zone dest user action category signature grandparent_process parent_process_id parent_process parent_process_name process_id process process_name file_path file_hash 
| nomv comment 
| sendalert thehive_create_a_new_case param.thehive_instance_id=3ce5b522 param.case_mode="regular_mode" param.source="" param.title="" param.description="" param.tags="test;CROWD" param.scope=1 param.severity="$result.th_severity$" param.pap=2 param.unique_id_field="event_hash"
```

3. Get unexpected observables fields

### Logs (issued from the search.log with logging mode set to DEBUG under Settings/Configuration)
Screenshot 1
<img width="395" alt="image" src="https://github.com/LetMeR00t/TA-thehive-cortex/assets/26856430/c58afcdb-42b3-467c-91bb-002d977b0784">

Screenshot 2
<img width="345" alt="image" src="https://github.com/LetMeR00t/TA-thehive-cortex/assets/26856430/3490fb54-c6fa-4fa7-933a-b54a92532cef">

Screenshot 3
<img width="473" alt="image" src="https://github.com/LetMeR00t/TA-thehive-cortex/assets/26856430/ed2d3a66-e23c-4a2f-9ee9-f6c8c28d81f1">
Debug info<img width="1231" alt="image" src="https://github.com/LetMeR00t/TA-thehive-cortex/assets/26856430/71b5a4d2-80db-4cff-bf38-6c02b9d37518">

**Comment by LetMeR00t** [comment]
Hello @tsserg99,

Be aware that the name of the fields are the one on the left on your Screenshot 1.
This means that **your splunk search needs to use "search-name" and not "search_name" as custom field** to be identified as is.
This is because of the way how custom fields are built in TheHive... And I'm using the key (on the left) instead of the custom field name rendered (right) as you can have tricky things such as spaces or whatsoever 

Let me know if this fixed your issue

**Comment by tsserg99** [comment]
Perfect. I changed my fields using "-" and it works. Thank you!
