### ISSUE TITLE
[BUG] Splunk SPL safeguards blocking hive as risky commands

### ISSUE THREAD

**Issue by maazbaig19** [LetMeR00t/TA-thehive-cortex#87]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | 
| TheHive version / git hash   |  5.2.12-1

### Problem Description
I am trying to install the Hive app on splunk, during the configuration splunk SPL is blocking the commands as risky, I opened a case with the Splunk support team and they are asking for those commands so I can send them to Splunk? So that the safeguards can be removed.

### Steps to Reproduce
Go to the TheHive/Cortex application > Settings > Instances
Add a new instance
Post adding all the information in the debug it is showing as splunk is identifying the commands as risky,
![image](https://github.com/LetMeR00t/TA-thehive-cortex/assets/12766422/227a92c5-ff00-45cc-9a73-14aa91b85041)

### Possible Solutions
-

### Logs (issued from the search.log with logging mode set to DEBUG under Settings/Configuration)
-

**Comment by LetMeR00t** [comment]
Hello @maazbaig19 
Any execution of a custom custom is considered as risky by default on Splunk.
All the commands are safe and can be trusted by Splunk.
Don't know if I have anything to do on my side for it?

**Comment by LetMeR00t** [comment]
Hello 
For all Python commands, everything is defined under the commands.conf file: https://github.com/LetMeR00t/TA-thehive-cortex/blob/main/TA-thehive-cortex/default/commands.conf

In your case, I’m wondering if we aren’t talking about few JavaScript scripts used to load data from the lookups.

in that case all the JavaScript scripts (4 in total at the end of the folder) are available here: https://github.com/LetMeR00t/TA-thehive-cortex/tree/main/TA-thehive-cortex/appserver/static

**Comment by maazbaig19** [comment]
This was resolved after disabling SPL safeguards
