### ISSUE TITLE
[BUG] Splunk Alert with multiple rows/events leads to failure

### ISSUE THREAD

**Issue by marpoe** [LetMeR00t/TA-thehive-cortex#90]
### Request Type
Bug

### Problem Description
If my Splunk Alert consists of multiple events (rows) and the alert setting is set to "ES notable mode" the TA should create one TheHive Alert for each row

### Steps to Reproduce
1.  Create a Splunk Alert
````
_time | url
2024-04-22 05:05:07 | www.test.com
2024-04-29 10:27:02 | www.test.com
2024-04-22 05:05:08 | www.test.com
2024-04-23 05:06:04 | www.test.com
````
![image](https://github.com/LetMeR00t/TA-thehive-cortex/assets/61042353/25b02bf0-a3a1-4d27-9f65-294a5c27ef9e)

3.  Run the Alert with Alert mode "ES notable mode" (1 alert per row). I tested the same with "Alert action mode" without a unique field.

5. Verify log output

````
error=CreateError - Alert alert:splunk:scheduler_cG9lbGxtcmtAc2NoYWVmZmxlci5jb20_c2NoYWVmZmxlcl9zb2M__RMD549035e33c4aa98f7_at_1714477620_73377_<xxxxxx> already exists in organisation Test" 

````

### Possible Solutions
- It loos like that the "reference field" has to be unique. Is there something what I've configured the wrong way?

![image](https://github.com/LetMeR00t/TA-thehive-cortex/assets/61042353/55e74d41-ef14-4aff-a4fe-4e84bf3a1c60)
-

**Comment by marpoe** [comment]
Ok, something to add. I saw it must be unique based on reference, source & type which can be filled based on the splunk alerts data. Can be fixed by this.

**Comment by LetMeR00t** [comment]
Hello @marpoe 
Thank you for submitting your issue 
In order to check first if we can make it work otherwise, could you add in your search something like ‘| eval unique=123456789’ to get a new column in your result 
Then run the custom alert action with the Alert Action mode and set the Unique ID field parameter to « unique » 
See if it’s working like that first or not

**Comment by marpoe** [comment]
Hello @LetMeR00t - Thank you for your reply.

As you suggested, I've created the following entries by my splunk search

_time | unique | url
-- | -- | --
2024-04-29 10:27:02 | 123456789 | www.test.com
2024-05-01 15:57:01 | 123456789 | www.test.com
2024-04-23 05:06:04 | 123456789 | www.test.com
2024-04-30 14:52:01 | 123456789 | www.test.com

Alert setting:
![image](https://github.com/LetMeR00t/TA-thehive-cortex/assets/61042353/b12c0a58-bf91-406d-a331-996788d7e8f8)

Result Log:
````
error=CreateError - Alert alert:splunk:123456789 already exists in organisation xxxxx"
````
Result TheHive:

![image](https://github.com/LetMeR00t/TA-thehive-cortex/assets/61042353/986e0cf5-6b81-48e3-9f1a-22eba3593640)

The "unique" value will be used as reference in TheHive. Due to the fact, that I'm using the same value for all 4 events, the creation fails. By ensuring a real unique value everything will work. No issue anymore in my opinion, just something to be aware of.

**Comment by LetMeR00t** [comment]
Hello,
I'm sorry for the late response.
Did you figured how to fix the issue or understand the root cause?
If it still relevant today for you, I can work on this during July 2024.
Thank you

**Comment by marpoe** [comment]
It's working by ensuring a unique value is present per row and the respective fieldname of this unique value is set in the alert action for "Unique ID field". No further action required, just to be aware of it. Thanks for your response & support!!
