### ISSUE TITLE
Check splunk connected with theHive

### ISSUE THREAD

**Issue by MohammadTtay** [LetMeR00t/TA-thehive-cortex#91]
### Request Type
Help Wanted

### Problem Description
theHive deployed on first server and i can access it like this : http://ip:9000
how can i connect my splunk on second server to theHive

If I want to explain in detail :
I have created an account for theHive .Then i have taken an API in my theHive and set the API as password of my account in this TA as in doc said .
can you help me in detail ?
![Screenshot 2024-05-26 143515](https://github.com/LetMeR00t/TA-thehive-cortex/assets/83585613/8d4c6d69-bb8b-493a-8c8e-deef9c8ee612)

**Comment by LetMeR00t** [comment]
Hi @MohammadTtay 
I don’t get your point sorry 
Isn’t adding a new instance what you want ?

**Comment by MohammadTtay** [comment]
Yes i do .
I just want to connect an instance
But I dont know how?
Actually i cannot be sure that my instance connected or not
Can you explain for me in detail ?

**Comment by LetMeR00t** [comment]
As soon as you have added it in the Instances lookup as shown, you can go in the dashboard used to get the alerts or the cases in the navigation bar. 
When selecting your instance in the dashboard using the corresponding input, you shall have the results shown in the dashboard.
If not (nothing shown and a little warning/error appears in the panels of the dashboard), check the « Audit Logs » dashboard for any error or check the job logs in details to find any error.

**Comment by LetMeR00t** [comment]
Hello @MohammadTtay 
Any update on this ?
Thank you

**Comment by MohammadTtay** [comment]
I should get certificate for my server which thehive running on it ?

**Comment by LetMeR00t** [comment]
Hello
I don’t get your point, did you have any log useful to determine what is the issue ?
Thank you

**Comment by LetMeR00t** [comment]
Hello 
I’m closing this old issue.
Let me know if you need further help.
Thank you
