### ISSUE TITLE
[BUG] Adaptative response **TheHive - Create a new alert** not saveable

### ISSUE THREAD

**Issue by tsnaketech** [LetMeR00t/TA-thehive-cortex#96]
### Request Type
Bug

### Work Environment

| Question                            | Answer                |
|------------------------------|--------------------|
| OS version (server)             |  Redhat               |
| TheHive version / git hash |  3.4                      |
| Splunk Version                   |  8.2.11                 |

### Problem Description
It is not possible to save the Adaptative response **TheHive - Create a new alert** on a correlation search. No popup appears when we press the Save button. Back to version 3.3. Others may have the same problem.

### Steps to Reproduce
1. Create a correlation search
2. Add Adaptative response **TheHive - Create a new alert**
3. Modify a Unique ID field, for example
4. Click on Save

### Possible Solutions
- I don't know

### Logs (issued from the search.log with logging mode set to DEBUG under Settings/Configuration)
- N/A

**Comment by LetMeR00t** [comment]
Hello 
Does any log appears in the splunkd.log or in the « Audit Logs » dashboard ?
Did you tried the same thing with a classic savedsearch and the same custom alert action ?  
Thank you

**Comment by LetMeR00t** [comment]
Hello,
Any update?
Thank you

**Comment by LetMeR00t** [comment]
Hello 
I’m closing this old issue. If you need further help, let me know
Thank you
